INSERT INTO erros_entity (date, description, level, log, origin) VALUES
('2021-07-16', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-16', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-16', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-16', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Comercial Golfinho'),
('2021-07-16', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Comercial Golfinho'),
('2021-07-16', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Comercial Golfinho'),
('2021-07-16', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Comercial Golfinho'),
('2021-07-16', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Comercial Golfinho'),
('2021-07-10', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-10', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-10', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-10', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Comercial Golfinho'),
('2021-07-09', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Comercial Golfinho'),
('2021-07-09', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Comercial Golfinho'),
('2021-07-09', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Comercial Golfinho'),
('2021-07-09', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Funerária Tudo de bom'),
('2021-07-09', 'Erro no cadastro do CPF', '0', 'Clientes cadastrou o CPF errado', 'Funerária Tudo de bom'),
('2021-07-09', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Funerária Tudo de bom'),
('2021-07-09', 'Erro no cadastro do CPF', '0', 'Clientes cadastrou o CPF errado', 'Funerária Tudo de bom'),
('2021-07-09', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-08', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Comercial Golfinho'),
('2021-07-08', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Comercial Golfinho'),
('2021-07-07', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Comercial Golfinho'),
('2021-07-07', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-07', 'Alerta de segurança', '1', 'Tentativa de acesso indevida', 'Funerária Tudo de bom'),
('2021-07-05', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Comercial Golfinho'),
('2021-07-05', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Comercial Golfinho'),
('2021-07-05', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Funerária Tudo de bom'),
('2021-07-05', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Funerária Tudo de bom'),
('2021-07-05', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Funerária Tudo de bom'),
('2021-07-05', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Funerária Tudo de bom'),
('2021-07-05', 'Erro no cadastro do CPF', '2', 'Clientes cadastrou o CPF errado', 'Funerária Tudo de bom'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Funerária Tudo de bom'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Funerária Tudo de bom'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Funerária Tudo de bom'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Funerária Tudo de bom'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Funerária Tudo de bom'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Funerária Tudo de bom'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Comercial Golfinho'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Comercial Golfinho'),
('2021-07-01', 'Tentativa de acesso frustrada', '0', 'Usuário tentou acessar sem autorização', 'Comercial Golfinho');


INSERT INTO user_entity (name, email, password) VALUES
('admin-api-erros', 'admin-dono@gmail.com', '12345678q');